apiVersion: run.ai/v2alpha1
kind: InteractiveWorkload
metadata:
  name: jupyter-job2
  namespace: runai-team-a
spec:
  name:
    value: jupyter-job2
  gpu:
    value: "0.1"
  image:
    value: jupyter/base-notebook
  jupyter:
    value: true
  ingressUrl:
    value: "https://runai-demo.runailabs.com/team-a/jupyter-job2"
  pvcs:
    items:
      pvc-fs2:
        value:
          existingPvc: true
          claimName: my-pvc
          path: /home/jovyan/work
          readOnly: false
