apiVersion: run.ai/v2alpha1
kind: TrainingWorkload # 
metadata:
  name: job-1  #  
  namespace: runai-team-a # 
spec:
  gpu:
    value: "1"
  image:
    value: gcr.io/run-ai-demo/quickstart
  name:
    value: job-1 # 
